# Generated by Django 2.0.4 on 2018-04-18 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEPDN2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('gamma', models.IntegerField(default=0)),
                ('neutron', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='date uploaded')),
                ('device', models.CharField(choices=[('DataEPDN2', 'EPDN2'), ('DataLuilin', 'Luilin')], max_length=256)),
                ('serial_num', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DataLuilin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('dose', models.DecimalField(decimal_places=7, max_digits=14)),
                ('flux', models.DecimalField(decimal_places=7, max_digits=14)),
                ('file_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DataFile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=32)),
                ('airport_from', models.CharField(max_length=256)),
                ('airport_to', models.CharField(max_length=256)),
                ('time_dep', models.DateTimeField()),
                ('time_arr', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('time_off', models.DateTimeField()),
                ('time_on', models.DateTimeField()),
                ('time_in', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256)),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='date uploaded')),
                ('matricule', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='file_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.FlightFile'),
        ),
        migrations.AddField(
            model_name='dataluilin',
            name='flight_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Flight'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='flight_file_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.FlightFile'),
        ),
        migrations.AddField(
            model_name='dataepdn2',
            name='file_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DataFile'),
        ),
        migrations.AddField(
            model_name='dataepdn2',
            name='flight_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Flight'),
        ),
    ]
