# Generated by Django 2.0.4 on 2018-04-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataluilin',
            name='spectrum',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airport_from',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airport_to',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flightfile',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
