# Generated by Django 2.0.4 on 2018-05-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_custompermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegratedDose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.DecimalField(decimal_places=7, max_digits=14, null=True)),
                ('gamma', models.DecimalField(decimal_places=7, max_digits=14, null=True)),
                ('neutron', models.DecimalField(decimal_places=7, max_digits=14, null=True)),
                ('datafile_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DataFile')),
                ('flight_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Flight')),
            ],
        ),
    ]
