# Generated by Django 2.0.4 on 2018-05-09 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_integrateddose'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(choices=[('DataEPDN2', 'EPDN2'), ('DataLiulin', 'Liulin')], max_length=255)),
                ('version', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='datafile',
            name='version_fk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.DeviceVersion'),
            preserve_default=False,
        ),
    ]
