# Generated by Django 2.0.4 on 2018-05-18 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180509_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype', models.CharField(choices=[('DataEPDN2', 'EPDN2'), ('DataLiulin', 'Liulin')], max_length=256)),
                ('serial_num', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='deviceversion',
            old_name='device',
            new_name='dtype',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='device',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='serial_num',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='version_fk',
        ),
        migrations.AddField(
            model_name='device',
            name='version_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.DeviceVersion'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='device_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Device'),
            preserve_default=False,
        ),
    ]
