# Generated by Django 2.0.4 on 2018-05-30 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180518_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHawk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('qfactor', models.DecimalField(decimal_places=7, max_digits=14)),
                ('bas_LET', models.DecimalField(decimal_places=7, max_digits=14)),
                ('haut_LET', models.DecimalField(decimal_places=7, max_digits=14)),
                ('file_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DataFile')),
                ('flight_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Flight')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='dtype',
            field=models.CharField(choices=[('DataEPDN2', 'EPDN2'), ('DataLiulin', 'Liulin'), ('DataHawk', 'Hawk')], max_length=256),
        ),
        migrations.AlterField(
            model_name='device',
            name='version_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.DeviceVersion'),
        ),
        migrations.AlterField(
            model_name='deviceversion',
            name='dtype',
            field=models.CharField(choices=[('DataEPDN2', 'EPDN2'), ('DataLiulin', 'Liulin'), ('DataHawk', 'Hawk')], max_length=255),
        ),
    ]
