# Generated by Django 2.0.4 on 2018-06-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180530_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bas_LET', models.DecimalField(decimal_places=7, max_digits=14)),
                ('haut_LET', models.DecimalField(decimal_places=7, max_digits=14)),
            ],
        ),
    ]
