# Generated by Django 2.0.4 on 2018-06-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='coefficient',
            name='device_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Device'),
            preserve_default=False,
        ),
    ]
