# Generated by Django 2.0.4 on 2018-06-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180604_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficient',
            name='start',
            field=models.DateField(),
        ),
    ]
