# Generated by Django 2.0.4 on 2018-06-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180604_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahawk',
            name='current',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datahawk',
            name='dose_equ',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datahawk',
            name='gamma_dose',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datahawk',
            name='temp',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datahawk',
            name='volt',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=14),
            preserve_default=False,
        ),
    ]
