# Generated by Django 2.0.4 on 2018-06-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180606_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integrateddose',
            old_name='gamma',
            new_name='bas_LET',
        ),
        migrations.RenameField(
            model_name='integrateddose',
            old_name='neutron',
            new_name='haut_LET',
        ),
    ]
