# Generated by Django 2.0.4 on 2018-06-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180607_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='dtype',
            field=models.CharField(choices=[('DataEPDN2', 'EPDN2'), ('DataLiulin', 'Liulin'), ('DataHawk', 'Hawk')], max_length=255),
        ),
    ]
