# Generated by Django 2.0.4 on 2018-07-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180607_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompermission',
            options={'managed': False, 'permissions': (('add_data', 'Add device and coefficent'), ('upload', 'Upload data'), ('view_data', 'View data'))},
        ),
    ]
