# Generated by Django 2.0.4 on 2018-07-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180716_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompermission',
            options={'managed': False, 'permissions': (('add', 'Add data'), ('upload', 'Upload data'), ('view', 'View data'))},
        ),
    ]
